# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_type',
            new_name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='warehouse', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='number',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(default='stocker', max_length=200),
            preserve_default=False,
        ),
    ]
