# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20161121_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='markdown',
            field=models.IntegerField(default=1),
        ),
    ]
