# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20161127_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo_event',
            old_name='type',
            new_name='event_type',
        ),
    ]
