# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20161127_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoutingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.FloatField(default=1.0)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='promo_event',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='promo_event',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='discoutingtable',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Product'),
        ),
        migrations.AddField(
            model_name='discoutingtable',
            name='promo_event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Promo_event'),
        ),
    ]
