# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20161127_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_event',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
