# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_promo_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
