# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_event',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
