# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_promo_event_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_event',
            name='staff',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='promo_event',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
