# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20161129_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_id',
            field=models.IntegerField(default=1),
        ),
    ]
